LBHackney-IT/lbh-housing-register

components/application/application-forms.tsx, components/eligibility/index.tsx, components/eligibility/not-eligible.tsx, lib/store/index.ts, lib/store/resident.ts, lib/types/resident.ts, pages/apply/index.tsx, pages/eligibility-checker/[[...step]].tsx
- Renaming the `user` store to `resident` for clarity (between who is a resident user and what is an admin user)
- Storing the `agreement` state within the resident store, so we don't keep asking them to agree whenever they re-load their application
=> Resident store

lib/hoc/whenEligible.tsx, pages/apply/[person]/[[...step]].tsx, pages/apply/index.tsx, pages/apply/overview.tsx
A new high-order component that restricts access to the application (`/apply`) if the use is ineligible for housing.
Any ineligible requests will be shown the `<EligibilityOutcome />` component which details further information and reasonings behind this decision (as stored against the resident state).
Undefined eligibility state means that the user has not taken the eligibility checker tool or we have no record of it, so we cannot currently determine if they are eligible or not - we should continue to allow them to apply, and the decision will be made as they progress through the application.
=> Prevent residents from accessing the application if they are ineligible

lib/utils/form-data.ts, pages/apply/[person]/[[...step]].tsx, pages/eligibility-checker/[[...step]].tsx
Simple change, swapping out the form identifiers for constants just to ensure consistency
=> Form step identifiers as constants - to prevent potential for error in the future

components/announcement.tsx, components/content/table.tsx, pages/index.tsx, styles/global.scss
Superficial changes to the start page:
1. Amending copy to match latest figma designs
2. Adding additional copy
3. Adding example of wait times (not currently driven by any data)
4. Wrapping wait times in the standard `<Accountment />` component (`info` variant is being used) - this does not currently match Figma, but we should probably stick to the design system here
=> HRT-48: Application start screen, adding example wait times

components/application/application-forms.tsx, components/breadcrumbs.tsx, components/delete-link.tsx, components/form/form.tsx, components/summary-list.tsx, data/forms/_test-form.json, data/forms/immigration-status.json, data/forms/person-details.json, data/forms/your-situation.json, lib/store/additionalResidents.ts, lib/store/index.ts, lib/store/resident.ts, lib/types/form.ts, lib/types/resident.ts, lib/utils/form-data.ts, lib/utils/resident.ts, pages/apply/[resident]/[[...step]].tsx, pages/apply/add-resident.tsx, pages/apply/index.tsx, pages/apply/overview.tsx, pages/eligibility-checker/[[...step]].tsx, styles/components/_summary-list.scss, styles/global.scss
Reworked the application overview section (`/application/overview`):
- List of people (including the main resident) as set by the resident store
- Ability to add/remove people to and from the application
- - Resolve clashes with duplicate slugs
- Storing resident / main residents form data
=> HRT-29: Application overview

components/application/agreement.tsx, lib/hoc/whenAgreed.tsx, pages/apply/[resident]/[[...step]].tsx, pages/apply/add-resident.tsx, pages/apply/index.tsx, pages/apply/overview.tsx
Previously: going directly to parts of the application form (like `/application/overview`) would show the contents even if the user was not shown the agreement page.
This change ensures they have agreed before being able to see anything under the `/application` directory.
=> Require agreement before showing the application form

components/button.tsx, components/delete-link.tsx, components/dialog.tsx, styles/global.scss
Not the tidiest of implementations, but quickly integrating as proof-of-concept.
To test:
1. Go to /application/overview
2. Add a new person
3. Click on the person's link to view their progress
4. At the bottom the 'delete link' should be visible, click on this
5. You should be shown the dialog in place of the link
6. On cancel, the link should be reinstated and the dialog removed
7. Alternatively: On confirmation you should be taken back to the overview and that person should be removed from the application
=> Dialog confirmation when trying to delete a resident from the application

lib/utils/application-forms.ts
Removed the residential status from the eligibility checker at the pre-application screen.
=> Residential status removed from eligibility checker

pages/apply/expect.tsx
Bedroom logic value was hardcoded and now it's being passed dynamically like it should have been.
=> Value dynamically passed

lib/utils/users.ts
Reduce cookie max age from 30 days to 1 hour.
=> HRT-320 cookie expiry

components/admin/other-members.tsx, components/admin/personal-details.tsx, lib/utils/adminHelpers.ts, lib/utils/dateOfBirth.ts, pages/applications/edit/[id]/[person]/edit-household-member.tsx, pages/applications/edit/[id]/[person]/index.tsx, pages/applications/edit/[id]/add-household-member.tsx
Stops date of birth from adding and hour for daylight saving.
Correctly displays and allows editing of gender description
=> Date mismatch and editing/displaying applicant and household member fixes

.circleci/config.yml, serverless.yml
We currently have the following warning in the pipeline:
`npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!`
This indicates the npm version used to generate the lock file was at least 7 which was introduced in Node v15. However the pipeline is setup to run Node v14 and also the Lambda runtime is using v14, so there's a conflict.
This updates both the pipeline and the Lambda runtime to use v16, so it matches the version currently used locally.
Also the docker image for Node executor has been updated to new version and also the build context has been updated to reference newly created CircleCi context.
=> TS-1277 Update to node 16

sentry.client.config.js, sentry.server.config.js
Disable sentry on other than staging and production environments
This will reduce the noise in the console on development environments and also makes working with Cypress easier until we've had a proper chance to resolve all the existing errors.
Check if we are running on staging or production environment and if so, enable Sentry.
=> Disable sentry on dev environments

pages/_document.tsx
Disable Google Tag Manager on other than production environment
This makes is easier to work with Cypress in development environment and also reduces unnecesary calls.
Render the tag manager script on production environment only
=> Disable ga on other than prod

.eslintrc, next.config.js, package.json
Please see merged PR: https://github.com/LBHackney-IT/lbh-housing-register/pull/391
Currently, the next build step in the pipeline will Lint all files for a build. As we have only just implemented linting rules, we want to disable this until we've cleaned and tested.
=> Changes linting rules for Next Build

.circleci/config.yml, .eslintignore, .eslintrc, components/admin/SearchBox.tsx, components/admin/sidebar.tsx, components/layout/staff-layout.tsx, cypress.config.ts, cypress/e2e/makeAnApplication.cy.ts, cypress/e2e/searchForAnApplication.cy.ts, cypress/pages/applications.ts, cypress/support/commands.ts, cypress/support/helpers.ts, lib/utils/googleAuth.ts, next.config.js, package-lock.json, package.json, pages/applications/index.tsx, pages/applications/search-results.tsx, serverless.yml, types/cypress.d.ts
https://hackney.atlassian.net/browse/TS-1585?atlOrigin=eyJpIjoiNmUyMTk4ZjkzNGI3NDllZjkyYjgxZDhmNDc3ZGJhNWIiLCJwIjoiaiJ9
*Note utility function changes outlined in ticket will be addressed in a seperate PR.
**What** 
- Implements a readOnly user type in googleAuth.ts that can be used to show or hide features based on cookie status. This follows a similar pattern to the way other features are shown for different user groups. If a user has readOnly group which isn't superseded by another higher group (any other group) then it will apply the readOnly status.
- Implements an e2e tests to prove this case, 
- As a product of this implementation, where linting errors have been raised components have been refactored to account for this,
- Updates the pipeline to run e2e tests against a build …
=> Ts 1585 housing reg view only implement new view only group in the app

.eslintrc, jest.config.ts, lib/types/application-status.spec.ts, lib/utils/googleAuth.spec.ts, lib/utils/googleAuth.ts, lib/utils/requestAuth.spec.ts, lib/utils/users.spec.ts, package-lock.json, package.json, testUtils/apiHelper.ts, testUtils/envVarsHelper.ts, testUtils/jwtTokenHelper.ts, testUtils/types.ts, testUtils/userHelper.ts
Add test coverage for googleAuth and related functions.
Files covered:
1. lib/utils/googleAuth.spec.ts
2. lib/utils/requestAuth.spec.ts
3. lib/utils/users.spec.ts
Currently we don't have any test coverage for the functions involved in authentication. In order to develop the application further we need to add appropriate test coverage for the functions and components we modify. 
This adds baseline test coverage for the functions that are involved in authentication.
Please note these tests are not opinionated about the current implementation, but cover the functionality as is. 
`requestAuth.ts` tests are lacking some mock setups due to the module structure which makes it difficult. Since this initial update is done without any refactoring or changes to the implementation this function is …
=> TS-1585 add test coverage for auth utils

.circleci/config.yml, .env.sample, components/admin/ApplicationHistory.tsx, components/admin/ApplicationsTable.tsx, components/admin/other-members.tsx, components/admin/utils/ApplicationHistoryHelpers.tsx, cypress.config.ts, cypress/e2e/searchForAnApplication.cy.ts, cypress/e2e/viewAnApplication.cy.ts, cypress/pages/applications.ts, jest.config.ts, lib/utils/googleAuth.spec.ts, lib/utils/googleAuth.ts, package-lock.json, package.json, pages/applications/index.tsx, pages/applications/search-results.tsx, pages/applications/view/[id]/[person]/index.tsx, pages/applications/view/[id]/index.tsx, types/nested-object-diff.d.ts
https://hackney.atlassian.net/browse/TS-1558?atlOrigin=eyJpIjoiZDQ4NDg0NzM4NThhNDFiN2EwYzc2MGUwZmQ5ZmE3YmEiLCJwIjoiaiJ9
**What**
- Updates the functionality in googleAuth for clarity and accuracy. Renamed to hasReadOnlyPermissionOnly and function explicitly checks for the group rather than knowing that hasAnyPremissions would be true. Also updates and expands tests to cover this,
- This PR doesn't cover the full suite of e2e tests to 'prove' the AC has been met. This will follow case by case. Some inital e2e tests have been added.
- In the relevant parts of the application, this new functionality is used to hide the features that are not available to a readOnly user. In many cases, the edit functionality was already hidden by canEditApplication (user must be a manager),
- Where linting …
=> FE Features

.circleci/config.yml
This is a temporary fix to allow the changes [in this PR](https://github.com/LBHackney-IT/lbh-housing-register/pull/396) to be propagated on Dev.
=> Disable firefox e2e tests

components/admin/CaseDetailsItem.tsx, components/admin/HorizontalNav.tsx, components/admin/assign-user.tsx, components/admin/other-members.tsx, components/admin/personal-details.tsx, components/admin/sensitive-data.tsx, cypress.config.ts, cypress/e2e/searchForAnApplication.cy.ts, cypress/e2e/viewAnApplication.cy.ts, cypress/pages/applications.ts, pages/applications/view/[id]/index.tsx
https://hackney.atlassian.net/browse/TS-1561?atlOrigin=eyJpIjoiYmU3MTRkNmU5YTJjNDRjNjg5YTZiZmU0MDkyYWQwYWUiLCJwIjoiaiJ9
**What**
- Extends e2e Test to make sure a read-only user cannot see edit items in the view page.
- Refactors AssignUser to avoid nested ternary, and some other minor refactoring where linting was required.  
**Why** 
We want to ensure a user with a read-only token cannot see edit buttons, or make changes.
**How**
Extends the page model to cover required items and expands the view an application test.
**Future**
Mock the API so we're not calling the dev database for search.
=> Ts 1561 housing reg view only hide remove household member edit household member assign and mark as sensitive from application overview page

cypress/e2e/addCase.cy.ts, cypress/e2e/addHouseholdMember.cy.ts, cypress/e2e/editHouseholdMember.cy.ts, cypress/e2e/unassigned.cy.ts, cypress/e2e/viewRegister.cy.ts, lib/utils/googleAuth.spec.ts, lib/utils/googleAuth.ts, pages/applications/add-case.tsx, pages/applications/edit/[id]/[person]/edit-household-member.tsx, pages/applications/edit/[id]/add-household-member.tsx, pages/applications/unassigned.tsx, pages/applications/view-register.tsx
Currently read only users can access certain edit and other pages directly. They should not be able to access these pages at all.
Read only users are authorized to view only certain pages and data. This update locks down the pages they shouldn't be able to access.
1. Update `getRedirect ` function with additional read only authorization check that'll direct users to access denied page if they are not allowed direct access to the page
2. Update the following pages by implementing the read only authorization check
2.1  `applications/edit/{applicationId}/{personId}/edit-household-member`
2.2 `applications/edit/{applicationId}/add-household-member`
2.3 `applications/View-register`
2.4 `applications/unassigned`
2.5 `applications/add-case`
3. Disable eslint rules where fixing the issue would …
=> TS-1571 lock down pages for read only users

cypress/e2e/editMainApplicant.cy.ts, pages/applications/edit/[id]/[person]/index.tsx
Currently read only users can access the edit main applicant page directly. This access must be removed.
We don't want read only users editing main applicant details.
Implement updated `getRedirect` function that supports checking for read only permissions.
Resolve the linting issues
=> TS-1569 - remove edit main applicant access from read only users

cypress.config.ts, cypress/e2e/pages/viewApplication.cy.ts, cypress/pages/viewApplication.ts, pages/applications/view/[id]/index.tsx
Hide assessment section from read only users.
Read only users shouldn't be able to see any of the details or features related to assessments.
Stop assessment section from rendering when user has read only permissions only. Also update the cypress command for nock to enable multiple APIs to be mocked at the same time.
Refactor test setups to keep things DRY and share as much of the setup functionality as possible. For example move API mocks from page models to Cypress comands.
=> TS-1564 hide assessment section from read only users

__tests__/pages/api/applications/[id]/complete.spec.ts, __tests__/pages/api/applications/[id]/evidence.spec.ts
There are two additional PATCH and POST endpoints that weren't covered in previous read only feature related tickets. These are:
POST: `/applications/[id]/evidence`
PATCH: `/applications/[id]/complete`
The `canUpdateApplication` function used for authorization in both endpoints has been covered already elsewhere, so this update just adds authorization related tests to ensure endpoints return correct status code based on the result of `canUpdateApplication` authorization function.
Read only users should not have access to perform either of those operations i.e. create evidence requests or complete applications.
Add tests to check that correct status code is returned based on the `canUpdateApplication` response.
Add full test coverage to both end points to cover error handling etc.
=> TS-1573 Add auth tests for complete and evidence endpoints

cypress/e2e/pages/reviewApplicant.cy.ts, pages/applications/view/[id]/[person]/index.tsx
This update reverts the changes made in https://github.com/LBHackney-IT/lbh-housing-register/pull/403 to ensure read only users can see the money and health details for the applicant.
=> TS- 1567 Make money and health sections visible for ro users

.circleci/config.yml, cypress.config.ts, cypress/e2e/searchForAnApplication.cy.ts, cypress/e2e/viewAnApplication.cy.ts, cypress/support/commands.ts, types/cypress.d.ts
https://hackney.atlassian.net/browse/TS-1637?atlOrigin=eyJpIjoiN2Y5YTY2MmU4ODQ1NDI3NGFmZjRkN2RlNzFmMmM3MzMiLCJwIjoiaiJ9
**What**
- Intercepts the HR API so that when test run, the dev API is no longer being called,
- Note on the pipeline the dev api env var is removed and is passing.
**Why**
- We don't want to engage with any 'real' APIs during the e2e testing process.
**How**
- We intercept the /applications/ListApplicationsByAssignedTo path on the /applications page using Nock and mock the response object, 
- By using cy.wrap in the login command, we can access the user object to pass to the new nock intercept (which requires user in the path and response),
- After some investigation, we also add the .persist method to the nock request ([see …
=> Ts 1637 housing reg view only ensure dev api is not being called e2e

.circleci/config.yml, sonar-project.properties
Currently SonarCloud is not reporting code coverage even though the reporting has been setup in jest. This update fixes the configuration to make the jest coverage reports available to sonar-scan job.
We want to see code coverage reports for exisitng code base and new changes
Persist the test coverage reports to make them available to sonar-scan job
Implement cypress code coverage to further improve coverage reporting
=> TS-1595 Fix test jet covarege config

.circleci/config.yml, cypress/e2e/cookies.cy.ts
***To be merged after https://github.com/LBHackney-IT/lbh-housing-register/pull/407 is successfully deployed to staging***
https://hackney.atlassian.net/browse/TS-1635?atlOrigin=eyJpIjoiODczNzk3MjM4ZGFhNGVhMDlhNmY2NjY0NDEwZDgwMjciLCJwIjoiaiJ9
**What**
- Adds view port testing pipeline configuration for e2e testing,
- Remove viewport inside tests.
**Why**
- As this is a public facing app we want to ensure that our tests can run on many browsers and screen sizes without error. 
**How**
- Configures viewportSize and viewportWidth as parameters to the --config flag in cypress job. Then a matrix workflow is setup to pass the various browsers and screen sizes required. 
**Future**
- As we expand test coverage, will look ensuring some tests start using touch based interactions.
=> Ts 1635 housing reg view only viewport testing

components/errors/error-summary.tsx, cypress.config.ts, cypress/e2e/pages/startApplicationLoggedIn.cy.ts, cypress/e2e/viewAnApplication.cy.ts, cypress/pages/agreeTerms.ts, cypress/pages/start.ts, cypress/support/commands.ts, lib/store/apiCallsStatus.ts, lib/store/application.ts, lib/store/index.ts, pages/apply/agree-terms.tsx, pages/apply/start.tsx, testUtils/applicationHelper.ts, testUtils/personHelper.ts, types/cypress.d.ts
Current Lambda function on production is running on Node v14 runtime. That version of Node is now out of support and we cannot deploy changes using that runtime anymore. As part of the read only access feature development work we have updated the project to use the latest LTS Node version, 20.17. However that introduced some critical bugs that will stop us from deploying to production until they are fixed.
We noticed an issue where sometimes initial signup details where lost when user progressed from the login stage to the household members view. After troubleshooting the issue locally it appeared that the application does not handle delayed API calls properly which is causing the database and the application local state (using Redux) to get out of sync.
When the issue occurs the flow of …
=> TS-1659 fix person details null overwrite bug

serverless.yml
Temporarily enable CloudFront Distribution logs on development to help us troubleshoot an issue.
=> Add CloudFront Distribution logging

serverless.yml
Remove the temporary CloudFront Distribution loggin that was enabled for troubleshooting purposes.
=> Remove cloudfront distribution logging

serverless.yml
The logs bucket is no longer needed, so this update removes it from the config.
=> Remove temporary cfd logs S3 bucket

components/admin/HouseholdMemberForm.tsx, components/admin/MainApplicantForm.tsx, cypress/e2e/pages/applications/edit/[id]/person/edit-household-member.cy.ts, cypress/e2e/pages/applications/edit/[id]/person/index.cy.ts, cypress/e2e/pages/applications/edit/add-household-member.cy.ts, cypress/pages/applications/edit/[id]/person/edit-household-member.ts, cypress/pages/applications/edit/[id]/person/index.ts, cypress/pages/applications/edit/add-household-member.ts, cypress/pages/viewApplication.ts, lib/gateways/internal-api.ts, pages/applications/edit/[id]/[person]/edit-household-member.tsx, pages/applications/edit/[id]/[person]/index.tsx, pages/applications/edit/[id]/add-household-member.tsx
Edit application related pages are not currently displaying and handling HR API errors correctly. This update adds better saving and error handling messages, so user is aware what's happening. Pages included:
`/applications/edit/[id]/[person]/index.tsx ` 
`/applications/edit/[id]/[person]/edit-household-member.tsx ` 
`/applications/edit/[id]/add-household-member.tsx ` 
User don't currently get enough feedback on what's happening on the page when data is saved or errors occur.
1. Show `Saving...` message to user when applications is saved 
2. Show error message when HR API call fails. This had to be added to the `MainApplicantForm` and `HouseholdMemberForm` components too due to way the pages are currently structured
3. Update the gateway method by removing the current status === 400 check …
=> TS-1703 Improve data and error handling on edit application pages

components/admin/other-members.tsx, components/dialog.tsx, cypress/e2e/pages/viewApplication.cy.ts, cypress/pages/viewApplication.ts, cypress/support/commands.ts, lib/gateways/internal-api.ts, pages/applications/view/[id]/index.tsx, types/cypress.d.ts
Currently when household member is deleted from the application any API call failures happen silently, so user is not aware that something went wrong. This update improves the error handling to make the errors visible.
User should be notified when the delete household member operation fails.
Update the `handleDelete` function to show error message when the API call fails. This page has a deletion confirmation dialog, so this update closes the dialog on error and then displays the error message on the page, so it's constintent with other error messages. 
Cypress test setup has also been updated to remove page level API mocks, so they are now using the Cypress commands which is how other tests currently work.
`updateApplication` function in `internal-api` has been updated to throw an error …
=> TS-1707 Improve error handling on view application page

components/admin/AddCaseAddress.tsx, cypress/e2e/addCase.cy.ts, cypress/e2e/pages/applications/add-case.cy.ts, cypress/pages/applications/add-case.ts, cypress/support/commands.ts, lib/gateways/internal-api.ts, pages/applications/add-case.tsx, types/cypress.d.ts
Currently users are not notified of any backend errors on `/applications/add-case` page. This is the page where officers can create new cases directly from the app without resident having to create one of their own first. This update improves the error handling by showing an error message if any of the API calls made during the process fail. Saving message has also been added to indicate that the application creation process is in progress after form submission. The process includes the following steps in the backend:
1. Create the application
2. Complete the application
3. Update the application status to `MANUAL_DRAFT` 
Users should get better feedback what's happening during the process. By adding error handling and saving status it's clear at all times what's happening in the backend. …
=> TS-1712 Improve error handling on add-case page

components/form/CheckboxesConditional.tsx, components/form/radioconditional.tsx, components/form/radios.tsx, components/loading/index.tsx, cypress/e2e/pages/agreeTerms.cy.ts, cypress/e2e/pages/apply/submit/additionalQuestions.cy.ts, cypress/e2e/pages/apply/submit/declaration.cy.ts, cypress/e2e/pages/apply/submit/ethnicityQuestions.cy.ts, cypress/pages/additionalQuestions.ts, cypress/pages/components.ts, cypress/pages/confirmation.ts, cypress/pages/declaration.ts, cypress/pages/ethnicity.ts, cypress/pages/rejection.ts, cypress/support/commands.ts, lib/hooks/useApiCallStatus.tsx, lib/store/application.ts, package.json, pages/apply/confirmation.tsx, pages/apply/not-eligible.tsx, pages/apply/submit/additional-questions.tsx, pages/apply/submit/declaration.tsx, pages/apply/submit/ethnicity-questions.tsx, types/cypress.d.ts
https://hackney.atlassian.net/browse/TS-1702?atlOrigin=eyJpIjoiNWU5OGVmZDE4YzM4NGYwN2IyZjQ0OWQyODJmYjU5ZGUiLCJwIjoiaiJ9
**What**
Ensure that promises are fulfilled before progressing on the apply/ pages
**Why**
This is an implementation of the original issue detailed https://github.com/LBHackney-IT/lbh-housing-register/pull/421
**How**
Where the action triggers middleware to save, the custom hook is implemented to keep track of the promise state.
Where the action triggers a thunk directly, error handling is added to the page and the thunk is adapted to return an error on unfulfilled promise.
=> TS-1702: adds error handling on apply pages

lib/hooks/useApiCallStatus.tsx, pages/apply/agree-terms.tsx, pages/apply/household/add-person.tsx, pages/apply/start.tsx, pages/apply/submit/additional-questions.tsx, pages/apply/submit/declaration.tsx, pages/apply/submit/ethnicity-questions.tsx
https://hackney.atlassian.net/browse/TS-1735?atlOrigin=eyJpIjoiYzczNjI1NWI3MGY2NDAxYThlNTBiMjJhYzNmMzZiMDUiLCJwIjoiaiJ9
**What**
- Moves the loading state management to the custom hook, 
- Allows an optional timeout to be set, where a visual delay could be useful before showing a loading text/spinner. 
**Why**
- Cleaner implementation that allows a pending state to be used in the page/component without getting the value,
- To avoid flashing, in some components/pages it can be beneficial to delay the loading state. For that reason, the hook can manage that by having a timeout value passed to it.
=> Delay loading state

cypress/e2e/pages/apply/start.cy.ts, lib/hooks/useApiCallStatus.tsx
Currently when transitioning between `start` and `agree-terms` pages start page form flashes briefly on the screen after save is complete and before user is pushed to the agree-terms page. 
We don't want the current page render again after save before user is pushed to the next page.
This update changes the `useApiCallStatus` hook to not clear the save status before `router.push` unless it's specifically requested by the hook consumer. This ensures the start page in this use case never renders again before the `router.push` is complete. Also update the start page test to ensure save status is cleared in case of rejected API call.
=> TS-1755 improve save handling on personal details page

.circleci/config.yml, cypress.config.ts, next.config.js, package-lock.json, package.json
https://hackney.atlassian.net/browse/TS-1756?atlOrigin=eyJpIjoiODJhYjYxZDdkMjg1NDI4YzkwNWFkMDI2MTFiZWRiZWUiLCJwIjoiaiJ9
**What**
Allows the pipeline to run without errors unrelated to the tests or code. 
- Disables Firefox in tests due to the chunk error. Some investigation of options to turn this back on has been done and can be completed at a later date. [See ticket](https://hackney.atlassian.net/browse/TS-1770?atlOrigin=eyJpIjoiOGNiYmZmNmFjNjE1NGY4ZGI3YThhMjAyZmZlNjc2ZDMiLCJwIjoiaiJ9)
- Disables the webpack bundle analyser. As this was triggering on each test run, a solution should be found to only run in development mode and not during testing. 
- Excludes tests in the local folder from running in the pipeline. The cypress.config will exclude the folder if the PIPELINE variable is …
=> Ts 1756 hr pipeline is broken due to nock config errors

cypress/e2e/local/managerActions.cy.ts
This local e2e test fills in a form as a resident first and then logs in as a manger to perform various actions against the application. This covers some of the core data update changes introduced by the recent changes, but is by no means a comprehensive test for all features. Individual pages have their own coverage, so this is just for checking that the core features work well in the context of the entire app.
=> TS-1781 add local e2e test for a manager

cypress/e2e/local/ineligibleApplicantUnder18.cy.ts
Fix a broken test that was missed in the earlier test tidy up [PR](https://github.com/LBHackney-IT/lbh-housing-register/pull/459).
=> Fix under 18 local e2e test

package-lock.json, package.json
Update `@sentry/nextjs` to version `7.119.2` to resolve security vulnerability in the `rollup` library. https://github.com/getsentry/sentry-javascript/releases/tag/7.119.2
=> TS-1790 update @sentry/nextjs

.circleci/config.yml, next.config.js, sentry.client.config.js, sentry.edge.config.js, sentry.server.config.js
**What**
- Sets the Sentry DSN to the value from sentry
- Reverts setting sentry vars in the next.config as they're set in Pipeline
- Cleans up duplications of ENVIRONMENT in sentry configs
- Deletes the hackney token rather than changing it's value if sent to sentry
=> Configures sentry

__tests__/pages/api/auth/generate.spec.ts, pages/api/auth/generate.tsx
Improve error handling on `/api/auth/generate` API endpoint.
Currently we are getting a lot of unhandled errors in Sentry for this endpoint caused by Probely scans. We would like to reduce the noise of unhandled errors by improving the API responses where appropriate.
1. Update the endpoint to return `400` if the request body parsing fails rather than always returning 500.
2. Remove `console.error(error);` which doesn't add any value in production setting
=> TS-1787 Improve error handling on api/auth/generate endpoint

cypress/e2e/local/eligibleApplicantWithMedicalCondition.cy.ts, cypress/e2e/local/eligibleApplicantsBothOver55.cy.ts, cypress/e2e/local/eligibleApplicationWithHouseholdMembers.cy.ts, cypress/e2e/local/eligibleMainApplicantOnlyOver55.cy.ts, cypress/e2e/local/managerActions.cy.ts, cypress/e2e/local/sampleForSingleEligibleApplicant.cy.ts, cypress/e2e/pages/apply/submit/ethnicityQuestions.cy.ts, lib/hooks/useApiCallStatus.tsx, pages/apply/submit/ethnicity-questions.tsx
https://hackney.atlassian.net/browse/TS-1810?atlOrigin=eyJpIjoiOGY4NzA4OTVkZTQxNDkwMWExMjIxYjJhZWIyMWIzODQiLCJwIjoiaiJ9
**What**
User testing noted an error with the setting of ethnicity data.
Previously, the useApiCall status hook was pushing to the next page after data was saved. In the case of the ethnicity page, the second part of the form on the page was being skipped over after the initial save event. This change addresses this, so a user can set values in the second level of the form.
**Why**
Makes the hook more flexible to scenarios like this and ensures the user can engage with the whole form.
**How**
This changes the hook so if a path isn't provided, it won't push to a new page. In the case of this page, the path is only set on the final step of the ethnicity form.
=> Ts 1810 housing register ethnicity questions

.circleci/config.yml, package-lock.json, package.json, scripts/fix-junit-xml.js
This PR introduces end to end tests to CircleCI builds on all branches.
Prior to this PR, end to end tests were only run on the `development` and `main` branches because they take around 11-15 minutes to complete. A typical full pipeline run including deployment looked like this:
This PR makes a bunch of changes to the CircleCI config to improve clock time of builds:
1. Remove the separate dependency installation step, instead relying on the Node orb's built in caching of  `~/.npm` for efficient `npm ci` dependency installs.
2. Consolidate the   `npm build` step and cache the build artefact, preventing the deployment steps from having to rebuild the app. This improves overall deployment time without impacting feature branch test runs.
3. Consolidate the "assume AWS role" steps into the …
=> Speed up end to end tests in CircleCI 

.circleci/config.yml
In #485 we optimised the build by merging two jobs into one: assuming the deployment role, and carrying out the deployment. The two steps passed an AWS credentials file between them using workspace persistence. Merging the jobs removed some spin-up time from the overall run.
However, in
https://app.circleci.com/pipelines/github/LBHackney-IT/lbh-housing-register/1613/workflows/68ba707c-0862-45cd-a55d-6940a82a64eb/jobs/7067/parallel-runs/0/steps/0-107 the deployment step failed because Serverless was unable to retrieve secrets from AWS.
It turns out this failure cropped up because the`lbh-hackit/aws_assume_role` orb/command uses environment variables but outputs a credentials file. Environment variables take precedence, therefore the orb effectively no-ops unless a clean environment is …
=> 🐛 Fix deployment by using assumed AWS role

.circleci/config.yml
In #487 we unset the AWS credential environment variables before running the deploy step, so that `aws-cli` would use the credentials stored on disk by the assume-role step.
However, it looks like the environment variables may be reset for each step, because although unsetting them in an SSH debug session succeeded, the deployment failed:
https://app.circleci.com/pipelines/github/LBHackney-IT/lbh-housing-register/1616/workflows/6a32b504-27fa-4824-b702-59fce56128e0/jobs/7102.
If that assumption is correct, this change will resolve the deployment failure by unsetting the environment variable in the same bash shell as the deploy command is run.
If this change continues to fail, then #487 wasn't an effective fix and we can revert both this and that change.
=> ci: Unset env var in CI build step

.circleci/config.yml
Deployed Lambda function is currently failing with `Runtime.ImportModuleError: Error: Cannot find module 'restana'`. This updates the workspace to include `node_modules` folder to make all dependencies available to the Lambda.
=> Add node_modules to paths to persist

package-lock.json, package.json
Fixes [CVE-2025-29927](https://nextjs.org/blog/cve-2025-29927) by updating next to 12.3.5
=> fix: update next to version 12.3.5
