LBHackney-IT/lbh-housing-register

components/applications/application-table.tsx
components/checkboxes.tsx
components/radios.tsx
components/stats.tsx

Type errors with:
- Checkboxes
- Radios
React errors / key index required for:
- Stats
- Application table: stats

Resolving errors

---

.env
README.md
package-lock.json
package.json

Updating out-of-date packages to reduce down number of vunerabilities found within packages.
Also updating README information for the new sections of the app, and restoring basic .env environment variables.

Updating packages and details

---

components/application/application-forms.tsx
components/breadcrumbs.tsx
components/delete-link.tsx
components/form/form.tsx
components/summary-list.tsx
components/tag.tsx
data/forms/_test-form.json
data/forms/immigration-status.json
data/forms/person-details.json
data/forms/your-situation.json
lib/store/additionalResidents.ts
lib/store/index.ts
lib/store/resident.ts
lib/types/application.ts
lib/types/form.ts
lib/types/resident.ts
lib/utils/application-forms.ts
lib/utils/form-data.ts
lib/utils/resident.ts
pages/apply/[resident]/[[...step]].tsx
pages/apply/add-resident.tsx
pages/apply/index.tsx
pages/apply/overview.tsx
pages/eligibility-checker/[[...step]].tsx
styles/components/_summary-list.scss
styles/global.scss

Reworking the person's overview section (`/application/[resident]`)
- Tidying display of "tasks" / forms by category title
- Adding progression status to each task (todo / check answers / done)
- Pre-filling forms the residents revisits with their previously answered data
/application/overview:
- Adding the remaining task countdown to the overview (x tasks to do)

HRT-50: Person's overview

---

components/application/application-forms.tsx
components/form/form.tsx
pages/apply/[resident]/[[...step]].tsx

In addition to the 'Save and continue' button, we now have the ability to be able to 'save and exit' -> returning the user to overview screen for that person

The ability to be able to save and exit the form journey between steps

---

components/panel.tsx
components/timeline.tsx
pages/apply/confirmation.tsx
pages/apply/overview.tsx
styles/global.scss

- Adds confirmation page for when a user has submitted their application.
- Adds new components ([panel](https://design-system.hackney.gov.uk/components/panel) and [timeline](https://design-system.hackney.gov.uk/components/timeline)) that are used within the page.
- Adds a submit button to the application overview.

HRT-51: feature/confirmation-page

---

data/forms/address-details.json
data/forms/person-details.json
domain/application.ts
domain/resident.ts
lib/gateways/applications-api.ts
lib/gateways/internal-api.ts
lib/store/additionalResidents.ts
lib/utils/form-data.ts
lib/utils/resident.ts
package-lock.json
package.json
pages/api/applications/index.ts
pages/apply/[resident]/[[...step]].tsx
pages/apply/add-resident.tsx
pages/apply/overview.tsx

- Adds an application to the API once all data is collected (via final submit)
- Uses API route within next.js to act as a proxy for the POST request
- Uses the data that is within the redux store
- Adds some extra fields to the forms
- Adds todos for when we can update an application with the API (currently can only create)

HRT-31: feature/save-application-data

---

data/forms/residential-status.json
lib/utils/application-forms.ts
lib/utils/form-data.ts
lib/utils/form.ts
lib/utils/resident.ts

[HRT-63] The form link and form itself are now incorporated into the app.
[HRT-63]: https://hackney.atlassian.net/browse/HRT-63

Residential Status Form

---

components/application/application-forms.tsx
components/form/dateinput.tsx
components/form/details.tsx
components/form/dynamic-field.tsx
components/form/form-group.tsx
components/form/input.tsx
data/forms/address-details.json
data/forms/address-history.json
lib/utils/form-data.ts
lib/utils/resident.ts
pages/apply/[resident]/[[...step]].tsx
styles/global.scss

Added 2 form parts(Address History and Current Accommodation) whereas the former isn't fully functional yet due to not having been integrated with the Hackney Address API. Date Input for months and years is currently hardcoded for the demo but will be fixed shortly after.

Address History & Current Accommodation

---

components/application/application-forms.tsx
components/form/form.tsx
components/form/radios.tsx
data/forms/income.json
lib/types/form.ts
lib/utils/form-data.ts
lib/utils/resident.ts
pages/apply/[resident]/[[...step]].tsx

HRT-90: Income and savings screens now in place.

Income and savings

---

lib/utils/resident.ts

https://hackney.atlassian.net/browse/HRT-79

Updated resident application form labels

---

components/button.tsx
pages/apply/index.tsx

Added background color to information table.
Added missing links
Added SVG icon to button link

HRT-117 - Updated registered overview page

---

data/forms/medical-needs.json

Updated page heading to text outlined in the design
Added inset text to yes question to outline a separate medical form needs to be completed if there are medical needs

Added inset text to medical needs page

---

data/forms/sign-in-verify.json
pages/apply/verify.tsx

Update verify page with [announcement](https://design-system.hackney.gov.uk/components/page-announcement) style.
Todo: we probably want to think about not using JSON form structure for this.

HRT-115 verify page

---

pages/apply/expect.tsx
pages/apply/household/index.tsx

Notes: 
- Values are currently hardcoded for this iteration.

What to expect screen

---

data/forms/new-person-details.json
data/forms/person-details.json
data/forms/sign-up-details.json

Add extra titles, update gender option.

Titles / gender

---

.env.sample
README.md
lib/gateways/applications-api.ts

Rename `.env` variables to match name of the housing register API.

Update .env variables

---

lib/utils/dateOfBirth.ts
lib/utils/resident.ts
pages/apply/[resident]/[section].tsx
pages/apply/[resident]/index.tsx

Fix extra steps for household members over 18.

Application steps for over 18s

---

components/application/application-forms.tsx
components/form/insettext.tsx
data/forms/medical-needs.json
lib/types/form.ts

Updated the medical needs page to include a question reveal underneath the title of the page.

Updated medical needs page

---

data/forms/residential-status.json
lib/utils/validation.ts

Checkboxes at the end of the form not validating properly, have removed required attribute.

Validation fix for residential status

---

components/header.tsx
components/layout/resident-layout.tsx
components/layout/staff-layout.tsx

Adds different context depending on resident / staff layout.

Adjust sign out text in header

---

data/forms/Situation/court-order.json
data/forms/Situation/legal-restrictions.json
data/forms/Situation/unspent-convictions.json

Legal restrictions question was showing the text area regardless of the answer provided by the user.

Your situation conditional question fix

---

pages/index.tsx

Redirect to /overview if user is signed in instead of showing the start page

---

.gitignore
lib/store/cognitoUser.ts
package-lock.json
package.json
pages/apply/start.tsx
pages/apply/verify.tsx
serverless.yml

- Update amplify usage
- Move dev dependencies
Reduces serverless build from 95MB to 59MB.

Reduce build size

---

README.md
lib/gateways/applications-api.ts
lib/store/application.ts
mocks/data/applications.js
package.json
pages/apply/overview.tsx

- Fix complete application step.
- Update usage of mocks

Complete application fix

---

data/forms/Situation/situation-armed-forces.json
lib/types/form.ts
lib/utils/form-data.ts
pages/applications/view/[id]/[person]/index.tsx
pages/apply/[resident]/your-situation.tsx

… to nextFormId in JSON to determine route based on gathered data from previous section.

HRT-239 - Add armed forces question

---

.circleci/config.yml

Assume housing context for staging.

Update CircleCi context

---

serverless.yml

Use correct certificate for staging.

Certificate fix

---

serverless.yml

Update serverless.yml security groups and subnets.

Serverless updates

---

pages/applications/view/[id]/[person]/index.tsx

Added a button that opens in a new window to the documents store

Added View Documents button to admin page

---

serverless.yml

Add extra environment variables to serverless.yml

Serverless env vars

---

data/forms/sign-up-details.json
pages/apply/[resident]/personal-details.tsx
pages/apply/not-eligible.tsx

…persons and show on summary. Copy change.

HRT-264 - NI number updates

---

.circleci/config.yml
lib/utils/__snapshots__/addressHistory.test.ts.snap
lib/utils/addressHistory.test.ts
lib/utils/addressHistory.ts
package.json

In addition to prettier, also run typescript and jest at build time. 
For bonus points we should upgrade to the latest version of next js and run eslint too.

More testing

---

domain/HousingApi.ts
lib/gateways/applications-api.ts
lib/store/application.ts
lib/types/evidence.ts
lib/utils/evidence.ts
pages/api/applications/[id]/evidence.tsx
pages/apply/submit/declaration.tsx

Create evidence request on submission.
Mirrors the changes made in the API: https://github.com/LBHackney-IT/lbh-housing-api/pull/28

HRT-228 - evidence requests

---

data/forms/Situation/medical-need.json

Add exit point during your situation flow.

HRT-267 - your situation exit

---

lib/gateways/notify-api.ts
lib/store/application.ts
lib/utils/medicalNeed.ts
pages/apply/submit/declaration.tsx

Fix issue with medical need emails not getting sent.

HRT-293 - medical needs email

---

lib/store/application.ts
pages/apply/[resident]/summary.tsx
pages/apply/not-eligible.tsx
pages/apply/submit/declaration.tsx

Fix email not sending by adding the reason for disqualification.

HRT-293: disqualify fix

---

components/admin/assign-user.tsx
components/admin/checkbox-list.tsx
components/admin/other-members.tsx
lib/utils/applicationQuestions.ts
lib/utils/checkboxListData.ts

- Show non EEA citizenship data
- simplify settled status
- react bug fixes
- copy updates
- remove unused imports

HRT-302 - Immigration status display in admin

---

pages/apply/not-eligible.tsx

HRT-343 - if API breaks applicant can be disqualified and eligible

---

components/layout/staff-layout.tsx
lib/utils/googleAuth.ts
pages/api/auth/exit.tsx

Remove hackney token on sign out.

HRT-321 staff sign out

---

components/admin/medical-details.tsx

Fix issue saving other members medical data.

HRT-347: medical data

---

components/admin/actions.tsx

Apply validation logic on bedroom need when assigned active status.
Fixes issue with assessment not being editable.

HRT-315: update assessment status

---

components/admin/assign-user.tsx
components/admin/sensitive-data.tsx

Adds options for officer to assign to themselves and to unassign
Moves sensitive data into own section.
Reloads page after reassignment

HRT-406 - assign to self

---

lib/utils/dateOfBirth.ts
lib/utils/form.ts
pages/apply/[resident]/address-history.tsx

HRT-331 - bedroom need if over 55

---

lib/hoc/withApplication.tsx
pages/apply/submit/declaration.tsx

Allows user to return to overview from declaration page.

HRT-400 - Editable after submitting

---

components/admin/NovaletReports.tsx

Show message when synced with Novalet and disable approve button to prevent resubmission

HRT-380 - reports UI

---

components/admin/sensitive-data.tsx
pages/applications/view/[id]/index.tsx

Adds in new logic for permissions and statuses allowed to edit applications. Removes unused imports.

HRT-440 - update edit statuses

---

lib/gateways/internal-api.ts
pages/applications/add-case.tsx

Adds complete application to internal api
Generates submitted date when addin a manual application

HRT-434 - add case manually submitted date

---

components/layout/resident-layout.tsx
lib/hoc/withApplication.tsx
pages/apply/[resident]/[section].tsx
pages/apply/[resident]/index.tsx
pages/apply/confirmation.tsx
pages/apply/expect.tsx
pages/apply/household/index.tsx
pages/apply/not-eligible.tsx
pages/apply/overview.tsx
pages/apply/verify.tsx

Redirects to homepage on signout and adds stability around browsing an application

HRT-413 - sign out

---

components/admin/ApplicationHistory.tsx

Fixed enum mismatch due to camelCase enums

Forced all even types without activityDetails to render

---

lib/gateways/applications-api.ts
pages/applications/view-register.tsx

Adds UI for number of applications in each filter group

feature/HRT-477 - Add counts to filters and list

---

lib/utils/axiosClients.ts

https://hackney.atlassian.net/browse/HRT-380

Set host header for axios client

---

pages/api/reports/internal/download.tsx

https://hackney.atlassian.net/browse/HRT-380

logged the response from the API

---

pages/api/reports/internal/download.tsx

https://hackney.atlassian.net/browse/HRT-380

forced report type to be a string

---

components/admin/actions.tsx

Re-added bidding number auto generate UI

bidding number changes

---

components/admin/actions.tsx
lib/gateways/internal-api.ts
pages/api/applications/[id]/index.tsx

Reverts LBHackney-IT/lbh-housing-register#369

Revert "bidding number errors surfaced"

---

components/admin/actions.tsx
lib/gateways/internal-api.ts
pages/api/applications/[id]/index.tsx

Hotfix - merge fix

---

pages/apply/sign-in.tsx
pages/index.tsx

Add a warning message to home and sign in pages. This informs users that the form is no longer in use.

HT-20-752 Add a warning message

---

pages/apply/sign-in.tsx
pages/index.tsx

Remove now unnecessary warning message

HT20-752 Remove warning message

---

.gitignore
.pre-commit-config.yaml
README.md

Add pre-commit hooks:
1. Stop direct commits to main and development branches
2. Check yaml formatting
3. Run ggshield

TS-1277 Add pre-commit hooks

---

.circleci/config.yml

Pin serverless to version 3 to test whether that resolves some permission issues in the pipeline.

Pin serverless to version 3

---

.circleci/config.yml
.gitignore
components/button.tsx
cypress.config.ts
cypress.env.json.sample
cypress/e2e/startApplication.cy.ts
cypress/pages/home.ts
cypress/support/commands.ts
cypress/support/e2e.ts
package-lock.json
package.json
pages/index.tsx
sonar-project.properties
tsconfig.json

https://hackney.atlassian.net/browse/TS-1580?atlOrigin=eyJpIjoiOTA5NTUwNmI5YjNiNDcxZWEwZTViNDc3YjRiODJjMTMiLCJwIjoiaiJ9
**What**
- Adds configuration and packages for cypress e2e tests
- Adds configuration to run Sonar in the pipeline
**Why** 
- We want to expand testing coverage to include some e2e tests
- We want sonar to check our code 
**How**
- Adds the required libraries and config to run cypress
- Updates the CI config to run cypress test on merge into development and make passing a requirement to build stage
- Updates CI config to run sonar in parallel with test step

Adds Cypress & Sonar

---

.circleci/config.yml
cypress/e2e/viewAnApplication.cy.ts
cypress/pages/applications.ts
pages/applications/view/[id]/index.tsx

https://hackney.atlassian.net/browse/TS-1561
**What**
e2e Tests failing on the pipeline when merging into development, but not locally. This addresses that issue. 
**Future**
Note the application is not currently mocked - future tickets in the sprit will address that.

Clean up Ts 1561 housing reg view only tests

---

components/admin/assign-user.tsx
components/admin/medical-details.tsx
components/admin/personal-details.tsx
components/pagination.tsx
lib/utils/axiosClients.ts
lib/utils/checkboxListData.ts
lib/utils/gender.spec.ts
lib/utils/gender.ts
lib/utils/medicalNeed.ts
lib/utils/users.spec.ts
lib/utils/users.ts
pages/api/address/[postcode]/index.ts
pages/api/admin/logout.tsx
pages/api/applications/[id]/complete.tsx
pages/api/applications/[id]/evidence.tsx
pages/api/applications/[id]/index.tsx
pages/api/applications/[id]/note.tsx
pages/api/applications/index.ts
pages/api/auth/exit.tsx
pages/api/auth/generate.tsx
pages/api/auth/verify.tsx
pages/api/notify/[template].tsx
pages/api/reports/internal/download.tsx
pages/api/reports/novalet/approve/[fileName].tsx
pages/api/reports/novalet/download/[fileName].tsx
pages/api/reports/novalet/generate.tsx
tsconfig.json

**What**
A few small bugfixes from sentry and sonar flagged issues. Specifically, it's [high severity](https://sonarcloud.io/project/issues?impactSeverities=HIGH&issueStatuses=OPEN%2CCONFIRMED&id=LBHackney-IT_lbh-housing-register) issues on sonar where changing things will not result in any fundamental code changes.
**How**
- Uses a more [comprehensive regex pattern](https://sonarcloud.io/project/security_hotspots?id=LBHackney-IT_lbh-housing-register) for testing emails, 
- Updates the [deprecated useSentry function](https://sonarcloud.io/project/issues?sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&branch=development&id=LBHackney-IT_lbh-housing-register&open=AZIen68Xz8HUI-QOaXfL),
- Removes [unnecessary && operator](https://sonarcloud.io/project/issues?impactSoftwareQualities=RELIABI …

Ts 1681 hr bugfixes

---

cypress/pages/agreeTerms.ts

Update test id to fix failing e2e tests in the pipeline.

Update test id

---

serverless.yml

Update bucket ownership controls and the bucket resource reference

Update cfd logs config

---

components/form/checkboxes.tsx
components/form/form.tsx
cypress/e2e/pages/agreeTerms.cy.ts
cypress/pages/agreeTerms.ts
cypress/pages/household.ts
lib/hooks/useApplicationUpdateStatus.tsx
lib/store/apiCallsStatus.ts
pages/apply/agree-terms.tsx
pages/apply/household/index.tsx
pages/apply/start.tsx

https://hackney.atlassian.net/browse/TS-1690?atlOrigin=eyJpIjoiNjM3MDBlZjg5OTRlNDc5MjhhMjVhZDVhYzBhZDJmMjgiLCJwIjoiaiJ9
**What**
- Implements the new slice on the agree conditions page to make sure patch is fulfilled before progressing to the next page
- Creates a custom hook to make this logic easier to repeat in other places.
**Why**
- This is a further implementation of the solution to the bug [detailed here](https://github.com/LBHackney-IT/lbh-housing-register/pull/421).

Adds tests for agree terms

---

cypress/e2e/pages/apply/agree-terms.cy.ts
cypress/e2e/pages/apply/sign-in.cy.ts
cypress/e2e/pages/apply/start.cy.ts
cypress/e2e/pages/apply/verify.cy.ts

https://hackney.atlassian.net/browse/TS-1730?atlOrigin=eyJpIjoiYzBiMmRkYjRmYWM4NDkyOGFhM2Y5YzllNDUyMzI2MDkiLCJwIjoiaiJ9
**What**
Implementation of these pages of the custom hook ([see from])(https://github.com/LBHackney-IT/lbh-housing-register/pull/421) was complete. 
This just tidies up the page structure - so that it matches a similar patten to the application pages folder.

Tidy pages

---

pages/apply/overview.tsx

https://hackney.atlassian.net/browse/TS-1733?atlOrigin=eyJpIjoiMGY0ZTQzODRhOGU2NDczYWI4YWUzNDdhNTkxOTcwMWUiLCJwIjoiaiJ9
**What**
Implements the memorised useSelector as detailed in here [https://github.com/LBHackney-IT/lbh-housing-register/pull/437]

Implements the memorised useSelector

---

components/admin/personal-details.tsx
components/admin/utils/ApplicationHistoryHelpers.tsx
components/form/textarea.tsx
components/summary-list.tsx
cypress/e2e/pages/viewApplication.cy.ts
cypress/pages/applications.ts
cypress/pages/viewApplication.ts
cypress/support/commands.ts
pages/applications/view/[id]/index.tsx
types/cypress.d.ts

##What
Added tests to the view applicant page
To test that the page behaves as expected and increase code coverage for the application

View application page tests

---

cypress.config.ts
domain/HousingApi.ts
lib/store/auth.ts
pages/apply/sign-in.tsx
pages/apply/verify.tsx
pages/index.tsx

**What**
Configuration for e2e testing to allow bypass verification. 
**Why**
Necessary to run e2e test locally.

config for local testing to work around the auth

---

components/summary/AddressHistory.tsx

https://hackney.atlassian.net/browse/TS-1765?atlOrigin=eyJpIjoiY2VmODNiYzNlNjMyNDAzMDk1Zjk0OGRlYzZlZGI2M2EiLCJwIjoiaiJ9
**What**
Corrects the incorrect variable that was changed in [previous merge](https://github.com/LBHackney-IT/lbh-housing-register/pull/422).

Correct map variable

---

cypress/e2e/local/addHouseholdMembersToHousehold.cy.ts
cypress/e2e/local/eligibleApplicationWithHouseholdMembers.cy.ts
cypress/e2e/local/eligibleMainApplicantOnlyOver55.cy.ts
cypress/e2e/pages/apply/[resident]/your-situation.cy.ts
cypress/pages/addPerson.ts
cypress/pages/apply/[resident]/personal-details.ts
cypress/pages/apply/[resident]/your-situation.ts
cypress/pages/household.ts
pages/apply/household/index.tsx

Local e2e tests for the following scenarios:
1.  Add household members to the household at the beginning of the application
2. Eligible main applicant only (over 55 years old)
3. Eligible application with household members
Also fixes the sample test flow.

TS-1769 local e2e eligible single over 55

---

cypress/e2e/local/eligibleApplicantsBothOver55.cy.ts

Add local e2e test for a scenario where both main applicant and household member, partner in this instance, are both over 55.

TS-1760 eligible applicants both over 55

---

cypress/e2e/local/eligibleApplicantWithMedicalCondition.cy.ts

Local e2e check that application is eligible when main applicant has a medical condition.

TS-1761 applicant with medical condition

---

cypress/e2e/local/addHouseholdMembersToHousehold.cy.ts
cypress/e2e/local/eligibleApplicantWithMedicalCondition.cy.ts
cypress/e2e/local/eligibleApplicantsBothOver55.cy.ts
cypress/e2e/local/eligibleApplicationWithHouseholdMembers.cy.ts
cypress/e2e/local/eligibleMainApplicantOnlyOver55.cy.ts
cypress/support/intercepts.ts
cypress/support/locale2eTestsHelper.ts

This update tidies up the local e2e tests to use common helper functions where possible. Tests haven't changed at all, so this is just refactoring.

Tidy up local e2e tests

---

components/content/paragraph.tsx
cypress/e2e/local/ineligibleApplicantSucessfullyRejected.cy.ts
cypress/e2e/local/ineligibleApplicantUnder18.cy.ts
cypress/pages/rejection.ts
pages/apply/[resident]/summary.tsx
pages/apply/not-eligible.tsx

https://hackney.atlassian.net/browse/TS-1763?atlOrigin=eyJpIjoiMWJjNjcyOTcwOTc1NGQ1MWIzMDY2NjNhYTZjYTMxOWMiLCJwIjoiaiJ9
**What**
- Local e2e test for applicant under 18,
- Refactors the confirmData into a try catch awaiting the two actions dispatched to get rid of the error below currently throwing on test.

Applicant under 18 test

---

components/content/paragraph.tsx
cypress/e2e/local/ineligibleApplicantNoRoomNeed.cy.ts
cypress/pages/rejection.ts
pages/apply/[resident]/index.tsx
pages/apply/not-eligible.tsx

https://hackney.atlassian.net/browse/TS-1762
**What**
- Adds a test to ensure rejection if no room need is true
- Adds an effect to only check eligibility if age changes or the accommodation needs section is complete
Note the abort fetching error is resolved by merge of https://github.com/LBHackney-IT/lbh-housing-register/pull/452

Adds a test for rejection for no bedroom need

---

cypress/e2e/local/ineligibleApplicantNoRoomNeed.cy.ts
cypress/e2e/local/ineligibleApplicantUnder18.cy.ts
cypress/e2e/pages/apply/[resident]/summary.cy.ts
cypress/support/commands.ts

https://hackney.atlassian.net/browse/TS-1783?atlOrigin=eyJpIjoiNzM1NmIyZWY1OWNmNGFmNThlZDRlNDZiODgwMDM1MWYiLCJwIjoiaiJ9
**What**
- Updates test to ensure if the notify email fails, it will still successfully call and complete the disqualification action. 
- Updates local e2e test to use common function.

Adds a test based on a failure to notify api

---

cypress/e2e/local/addHouseholdMembersToHousehold.cy.ts
cypress/e2e/local/eligibleApplicantWithMedicalCondition.cy.ts
cypress/e2e/local/eligibleApplicantsBothOver55.cy.ts
cypress/e2e/local/eligibleApplicationWithHouseholdMembers.cy.ts
cypress/e2e/local/eligibleMainApplicantOnlyOver55.cy.ts
cypress/e2e/local/ineligibleApplicantNoRoomNeed.cy.ts
cypress/e2e/local/ineligibleApplicantUnder18.cy.ts
cypress/e2e/local/managerActions.cy.ts
cypress/e2e/local/sampleForSingleEligibleApplicant.cy.ts

Update all local e2e tests to support multiple back to back test runs. All tests have been updated to generate unique application id and email on every run. Couple of tests have also been updated to support the more streamlined setup.

Update local e2e tests to support multiple runs

---

cypress.config.ts
package-lock.json
package.json
pages/_app.tsx
pages/_document.tsx
pages/api/applications/throw-error.ts
pages/applications/throw-error.tsx

**What**
- Adds a testing page to check headers being passed, 
- Removes dotenv to test conflict with next.js

Testing page for sentry

---

next.config.js

Testing debug

---

.env.sample
.husky/pre-push
README.md
cypress.config.ts

https://hackney.atlassian.net/browse/TS-1803?atlOrigin=eyJpIjoiM2FhY2U3YzU3YTZiNDE1ZTljNmRkNWQzMTQxYjA3ZTEiLCJwIjoiaiJ9
**What**
- Updates readme to reflect changes to the app,
- Add a e2e test run on the pre-push hook,
- Changes the pipeline variable to e2e_local which better reflects the nature of the variable,

Ts 1803 hr update readme

---

.circleci/config.yml

**What**
Ensures tests and sonar scan are complete before building to stage or development sites.

Updates config for test before build

---

pages/_app.tsx
pages/_document.tsx

https://hackney.atlassian.net/browse/TS-1849?atlOrigin=eyJpIjoiZjY2YzhmNmRjNTNmNGNmOWFlMTllZjQ5NTc4MDYwMGMiLCJwIjoiaiJ9
**What**
- GTM ID is in the head but not being received. 
- This PR removes the ID from _App and uses the recommended configuration in __document only.

Updates the analytics config

---

.circleci/config.yml

Triggers the development build on merge into main (rather than develop). 
Following this, a merge of the RP PR will trigger a build onto Stage and Production.

ci(circle config): updates build to run on main

---

.circleci/config.yml

Updates config to run on version tag not label.

fix(circle config): updates to trigger on version number
